#! /usr/bin/env bash

# Warfacebot Daemon launcher
# Usage: ./wbd_launcher <botname> <realm>
#
# This is only useful if you are using the DBUS API
# to create a front-end such as a webserver.
#
# What it does:
# - Obtains a login token
# - Launches the daemon bot
#
# You can launch as many bot daemons as wanted.

cd $(dirname $0)

bot=$1
shift

# Credentials

declare -A logins
declare -A passwords

#Fixme
logins["bitch6"]="devilsbitch6@leeching.net"
logins["bitch7"]="devilsbitch7@leeching.net"

#Fixme
passwords["bitch6"]="ddbitch6"
passwords["bitch7"]="ddbitch7"


# Launch the daemon bot

WB_AS_DAEMON=1
login=${logins[$bot]}
psswd=${passwords[$bot]}

export login
export psswd

run mintty ./wb.sh "eu"
