#! /usr/bin/env bash

# Warfacebot Daemon launcher
# Usage: ./wbd_launcher <botname> <realm>
#
# This is only useful if you are using the DBUS API
# to create a front-end such as a webserver.
#
# What it does:
# - Obtains a login token
# - Launches the daemon bot
#
# You can launch as many bot daemons as wanted.

cd $(dirname $0)

bot=$1
shift

# Credentials

declare -A logins
declare -A passwords

#Fixme
logins["snip"]="snip@snip.com"
logins["snip2"]="snip2@snip.com"

#Fixme
passwords["snip"]="snip"
passwords["snip2"]="snip"


# Launch the daemon bot

[ -z ${logins[$bot]} ] && echo "Bot '$bot' not found" && exit 1

WB_AS_DAEMON=1 \
    login=${logins[$bot]} \
    psswd=${passwords[$bot]} \
    ${build}/wb.sh "$@" "-ddbus_id=${bot}"
